all:
  children:
    rhel8_servers:
      hosts:
        34.100.153.118:
        34.93.73.193:
      vars:
        ansible_user: root
        ansible_password: admin@123
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
