all:
  children:
    rhel8_servers:
      hosts:
        34.93.87.226:
        34.47.172.140:
      vars:
        ansible_user: root
        ansible_password: admin@123
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
