---
- name: Run Python Script
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Run Python Script
      command: python3 gcp-vCPUandRam-updator.py
      args:
        chdir: "{{ playbook_dir }}"
      register: script_output  # Captures the script output

    - name: Show Script Output
      debug:
        msg: "{{ script_output.stdout }}"  # Displays the captured output

