---
- name: Run Python Script
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Run Python Script
      command: python3 gcp-vCPUandRam-updator.py
      args:
        chdir: "{{ playbook_dir }}"
